### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Onako2** [PurpurMC/PurpurClient#23] opened 2022-09-05 17:47 UTC
[Pehkui](https://github.com/Virtuoel/Pehkui) is conflicting with [Purpur Client](https://github.com/PurpurMC/PurpurClient).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_1501::pehkui$updatePassengerPosition$offset with priority 1000 cannot inject into net/minecraft/class_1501::method_5865(Lnet/minecraft/class_1297;)V merged by org.purpurmc.purpur.client.mixin.mob.MixinLlama with priority 1000 [PREINJECT Applicator Phase -> pehkui.mixins.json:LlamaEntityMixin from mod pehkui -> Prepare Injections ->  -> constant$hbn000$pehkui$updatePassengerPosition$offset(F)F -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_1299.<clinit>(class_1299.java:217)
	at net.minecraft.class_7113.<clinit>(class_7113.java:34)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1061)
	at net.minecraft.class_5872.<clinit>(class_5872.java:9)
	at net.minecraft.class_5871.method_33968(class_5871.java:20)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.class_5871.<clinit>(class_5871.java:16)
	at net.minecraft.class_2939.<clinit>(class_2939.java:32)
	at net.minecraft.class_5463.<clinit>(class_5463.java:21)
	at net.minecraft.class_5458.method_30572(class_5458.java:66)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

```

## Mod list
```
- abtools 1.0.1
- additionaladditions 5.0.2
- adorn 3.6.1+1.19
- advanced_reborn 1.0.8
- advanced_runtime_resource_pack 0.6.4 via dynamic_asset_generator
- advancednetherite 1.6.4-1.19.2
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- ae2 12.1.2-beta
- ae2wtlib 12.1.0-beta
- alloy_forgery 2.0.15+1.19
- almostunified 0.0.4
- alternate-current 1.4.0
- amethyst_core 0.2.3+1.19
- amethyst_imbuement 1.19-08
- animatica 0.5+1.19
- antishulkerdupe 1.0.0
- appleskin 2.4.1+mc1.19
- aqupdgrizzly 1.19.2-1.3
- aqupdhat 1.19-2.3.2
- archeology 0.1.10
- architectury 6.2.43
- authme 4.1.0
- autoconfig1u 3.4.0 via advanced_reborn
- automaticdoors-fabric 2.8
- autosmeltenchant 1.1.0
- badpackets 0.2.0
- balm-fabric 4.5.2+0
- bamboocombat 1.0.2
- bendy-lib 2.1.1
- betteranimalsplus 1.19-11.0.7
- betteranimationscollection 4.0.1
- betterbeds 1.2.0
- bettermounthud 1.1.4
- bettersleeping 0.6.1+1.19
- bettersleeping-core 0.6.1 via bettersleeping
- biomemakeover 1.19.2-1.5.12
- biometech 0.1.1
- blockrunner 4.2.0
- bloodshed 1.0.3
- blossom 1.0.5
- blue_endless_jankson 1.2.1 via jankson
- blur 2.6.0
- boat-with-everything 1.1.0
- boatcontainer 1.2.3
- boatiview 0.0.4
- bobby 4.0.0
- borderlessmining 1.1.5+1.19
- byg 2.0.0.10
- c2me 0.2.0+alpha.8.37
- c2me-base 0.2.0+alpha.8.37 via c2me
- c2me-client-uncapvd 0.2.0+alpha.8.37 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.8.37 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.8.37 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.8.37 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.8.37 via c2me
- c2me-notickvd 0.2.0+alpha.8.37 via c2me
- c2me-opts-allocs 0.2.0+alpha.8.37 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.8.37 via c2me
- c2me-opts-chunkio 0.2.0+alpha.8.37 via c2me
- c2me-opts-math 0.2.0+alpha.8.37 via c2me
- c2me-opts-scheduling 0.2.0+alpha.8.37 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.8.37 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.8.37 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.8.37 via c2me
- c2me-server-utils 0.2.0+alpha.8.37 via c2me
- c2me-threading-chunkio 0.2.0+alpha.8.37 via c2me
- c2me-threading-lighting 0.2.0+alpha.8.37 via c2me
- c2me-threading-scheduling 0.2.0+alpha.8.37 via c2me
- c2me-threading-worldgen 0.2.0+alpha.8.37 via c2me
- caffeineconfig 1.0.0+1.17 via sodium-extra
- calcmod 1.1.0
- camp_fires_cook_mobs 1.2.9
- capetweaks 1.0.1
- cardinal-components-base 5.0.1 via puzzleslib
- cardinal-components-block 5.0.1 via puzzleslib
- cardinal-components-chunk 5.0.1 via puzzleslib
- cardinal-components-entity 5.0.1 via puzzleslib
- cardinal-components-world 5.0.1 via puzzleslib
- carpet 1.4.83
- celestria 1.1.1
- charm 4.2.2
- charmonium 4.1.0
- chromablocks 2.0.0-1.19.2
- citresewn 1.1.1+1.19
- citresewn-defaults 1.1.1+1.19 via citresewn
- clickthrough 1.19.1-fabric0.58.5-0.4
- clientarguments 1.4.1 via calcmod
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.0.75
- cloth-config-lite 2.0.6 via mealapi
- cmods 1.3.1+fabric-1.19
- coat 1.0.0-beta.18+mc22w17a via wandering_collector
- collective-fabric 4.50
- coloredglowlib 1.4.0
- colorfulanvils 1.0.2+1.19.1
- com_electronwill_night-config_core 3.6.5 via c2me
- com_electronwill_night-config_toml 3.6.5 via c2me
- com_eliotlash_mclib_mclib 18 via geckolib3
- com_eliotlash_molang_molang 18 via geckolib3
- com_github_cosmetica-cc_cosmeticadotjava 1.5.2 via cosmetica
- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
- com_github_luben_zstd-jni 1.5.2-2 via dashloader
- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 via textile_backup
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via charm
- com_typesafe_config 1.4.2 via bobby
- common-protection-api 1.0.0 via biometech
- compact_storage 5.0.3-1.19.1
- conditional-mixin 0.3.0 via cull-less-leaves
- confabricate 3.0.0-SNAPSHOT+4.1.2 via purpurclient
- cookedcarrots 1.19.2-5
- copperhopper 0.0.11+1.19.2
- coppertier 1.0
- cosmetica 1.2.0
- craftingbench 0.4-BETA+1.19
- crops_love_rain 1.3.0
- crowdin-translate 1.4+1.19 via durabilityviewer
- crystals 0.0.1-1.19.2
- ctov 3.1
- cull-less-leaves 1.0.5
- cullleaves 2.3.4
- customlan 1.19.1-v2.1.0
- customportalapi 0.0.1-beta54-1.19 via serbanmod
- cyclepaintings-fabric 2.6
- darkness-in-the-bottle 1.0.2
- dashloader 4.1.2+1.19
- dawn 3.5.0
- de_poiu_apron_apron 2.1.1 via mconfig
- debugify 2.5.0
- defaultoptions 15.0.0
- dev_quantumfusion_hyphen 0.2.2 via dashloader
- dev_quantumfusion_taski 1.1.0 via dashloader
- diamondchestshop 1.2.3-1.19
- diamondeconomy 1.5.2
- dungeons_arise 2.1.51
- durabilityviewer 1.19.1-fabric0.58.5-1.10.3
- dynamic_asset_generator 1.0.1
- dynamicfps 2.2.0
- eatinganimationid 1.9
- editsign 2.6.0
- emeraldtier 1.0
- emi 0.3.4+1.19
- emotecraft 2.2.5
- emuno 0.2.1
- enderism 1.2.0
- energized_redstone 1.0.1-prerelease
- enhancedgear 1.2.0-1.19.2
- enhancedswords 1.0.0-1.19.x
- entity-view-distance 1.0.2+1.19
- entity_texture_features 4.0.2
- entitycollisionfpsfix 2.0.0.0
- entityculling 1.5.2-mc1.19
- error_notifier 1.0.9 via roughlyenoughitems
- extended_drawers 1.3.3+mc.1.19.1
- extrabars 1.0.0
- extrasounds 2.3.1+1.19.2-1.19.1
- extrasponges 1.4.1
- extrastairs 1.1.0
- fabric-api 0.60.0+1.19.2
- fabric-api-base 0.4.11+e62f51a390 via fabric-api
- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
- fabric-language-kotlin 1.8.3+kotlin.1.7.10
- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
- fabric-permissions-api-v0 0.2-SNAPSHOT via colorfulanvils
- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via resclone
- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
- fabricloader 0.14.9
- fabrishot 1.8.0
- fallingleaves 1.12.2+1.19.2
- fallingtree 3.9.2
- farmersdelight 1.19-1.3.3
- faster_entity_animations 1.5.3
- ferritecore 4.2.1
- fiber 0.23.0-2 via patchouli
- fireflallymod 1.3.0
- flamearrows 1.19.2-11
- forcecloseloadingscreen 1.1.1
- forgeconfigapiport 4.2.6
- forgetmechunk 1.0.4-1.18.X-1.19.X
- frame 0.26.1+1.19-fabric
- frame-api-base 0.2.1+906ebc04a9 via frame
- frame-blocks-v0 0.1.3+233e7428a9 via frame
- frame-config-v0 0.3.1+0fa45150a9 via frame
- frame-content-registries-v0 0.4.0+2876b511a9 via frame
- frame-enchantments-v0 0.1.0+4093105da9 via frame
- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
- frame-items-v0 0.1.3+906ebc04a9 via frame
- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
- frame-rendering-v0 0.1.5+906ebc04a9 via frame
- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
- frame-woods-v0 0.2.1+6a33fbada9 via frame
- fuelinfo 1.0.1+1.19
- fwaystones 3.0.3+mc1.19.2
- gbfabrictools 1.3.4+1.19 via durabilityviewer
- gearreborn 1.19-0.1.15
- geckolib3 3.1.17
- geodes 1.5
- graphlib 0.3.1+1.19 via wiredredstone
- headfix 1.2.0
- holdthatchunk 1.1.1
- hologram-api 0.2.2+1.19 via biometech
- icy-incitement 1.1.4+1.19.x
- illagerexp 1.0.0
- indium 1.0.9+mc1.19.2
- infinitybuttons 1.3.0-mc1.19
- io_leangen_geantyref_geantyref 1.3.13 via bobby
- iris 1.2.8
- itemmodelfix 1.0.3+1.19
- jamlib 0.4.4
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- journeymap 5.9.0beta2
- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT via journeymap
- justplayerheads-fabric 2.4
- kanos_config 0.3.1+1.14.4-1.19 via pehkui
- kibe 1.9.9-BETA+1.19
- kirin 1.11.0 via presencefootsteps
- lambdynlights 2.1.2+1.19
- languagereload 1.3.2
- lazy-language-loader 0.3.1
- lazydfu 0.1.3
- letmedespawn fabric-1.0.2
- lib39 1.2.1
- lib39-core 1.2.1 via lib39
- lib39-crowbar 1.2.1 via lib39
- lib39-deferral 1.2.1 via lib39
- lib39-dessicant 1.2.1 via lib39
- lib39-fractal 1.2.1 via lib39
- lib39-gesundheit 1.2.1 via lib39
- lib39-keygen 1.2.1 via lib39
- lib39-lockpick 1.2.1 via lib39
- lib39-machination 1.2.1 via lib39
- lib39-phantom 1.2.1 via lib39
- lib39-recoil 1.2.1 via lib39
- lib39-ripple 1.2.1 via lib39
- lib39-sandman 1.2.1 via lib39
- lib39-tunnel 1.2.1 via lib39
- lib39-util 1.2.1 via lib39
- lib39-waypoint 1.2.1 via lib39
- lib39-weld 1.2.1 via lib39
- libblockattributes_core 0.11.0-pre.1.3+kneelawk via libmultipart_deps_container
- libgui 6.0.0+1.19 via rpgstats
- libjf 3.1.0
- libjf-base 3.1.0 via libjf
- libjf-config-core-v1 3.1.0 via libjf
- libjf-config-legacy-shim 3.1.0 via libjf
- libjf-config-reflect-v1 3.1.0 via libjf
- libjf-config-ui-tiny-v1 3.1.0 via libjf
- libjf-data-manipulation-v0 3.1.0 via libjf
- libjf-data-v0 3.1.0 via libjf
- libjf-devutil-v0 3.1.0 via libjf
- libjf-translate-v1 3.1.0 via libjf
- libjf-unsafe-v0 3.1.0 via libjf
- libjf-web-v0 3.1.0 via libjf
- libmultipart 0.8.0-pre.1.5+kneelawk via libmultipart_deps_container
- libmultipart_deps_container 0.8.0-pre.1.5+kneelawk via wiredredstone
- libnetworkstack 0.7.1-pre.0.3+kneelawk via libmultipart_deps_container
- libninepatch 1.1.0 via libgui
- lightoverlay 7.0.0
- lithium 0.8.3
- loadingscreentips 1.0.2
- logicgates 1.3.5
- logprot 1.19.1-1.6
- lovely_snails 1.1.0+1.19
- mconfig 1.2.0+mc.1.19-rc1 via extended_drawers
- mcpitanlib 1.4.4 via advanced_reborn
- me_lucko_spark-api 0.1-SNAPSHOT via servercore
- mealapi 0.3.1+1.19
- megane 8.2.0
- megane-alloy-forgery 8.2.0 via megane
- megane-api 8.2.0 via megane
- megane-applied-energistics-2 8.2.0 via megane
- megane-fabric-transfer 8.2.0 via megane
- megane-kibe 8.2.0 via megane
- megane-reborn-core 8.2.0 via megane
- megane-reborn-energy 8.2.0 via megane
- megane-runtime 8.2.0 via megane
- megane-tech-reborn 8.2.0 via megane
- megane-vanilla 8.2.0 via megane
- memoryleakfix 1.19.1-0.7.0
- memoryusagescreen 1.6
- midnightcontrols 1.5.0+1.19
- midnightlib 0.6.0
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- mm 2.3 via enderism
- modbattle v1.2.5-mc_1.19.2
- modmenu 4.0.6
- moreculling 1.19.1-0.10.0
- morediscs 1.19.2-17
- morefrogs 1.19.x-1.2.2-fabric
- morepotions 1.0.2
- mossierdeepslate 2.0.1
- mythicmetals 0.15.4
- nbtcrafting 2.1.4+mc1.19
- netheritebeacons 1.2.0
- netherwardblock 1.19.2-6
- no_tutorial_toast 1.0.0
- nochatreports 1.19.2-v1.11.1
- noindium 1.0.2+1.18.2 via ae2
- notenoughanimations 1.6.1
- notenoughcrashes 4.1.6+1.19
- numeralping 1.0.4
- omega-config 1.2.3-1.18.1 via noindium
- openblocks 0.0.1-1.19.X
- org_anarres_jcpp 1.4.14 via iris
- org_apache_commons_commons-compress 1.21 via textile_backup
- org_apache_commons_commons-text 1.9 via bettersleeping
- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_mariuszgromada_math_mathparser_org-mxparser 5.0.6 via calcmod
- org_spongepowered_configurate-core 4.1.2 via bobby
- org_spongepowered_configurate-extra-dfu4 4.1.2 via confabricate
- org_spongepowered_configurate-gson 4.1.2 via confabricate
- org_spongepowered_configurate-hocon 4.1.2 via bobby
- org_threadly_threadly 7.0 via c2me
- org_tukaani_xz 1.9 via textile_backup
- org_xerial_sqlite-jdbc 3.36.0.3 via diamondeconomy
- owo 0.7.3+1.19
- packet_tweaker 0.3.0+1.18.2 via server_translations_api
- patchouli 1.19.2-76-FABRIC
- pehkui 3.4.1+1.14.4-1.19.2
- pinlib 0.1.3+1.19 via fwaystones
- placeholder-api 2.0.0-beta.7+1.19 via servercore
- player-animator 0.3.5
- playerabilitylib 1.6.0 via amethyst_imbuement
- plentyofarmors 1.0.2
- polymer 0.2.15+1.19.2 via biometech
- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
- presencefootsteps 1.6.1
- pride 1.1.2+1.19 via lambdynlights
- puddles 1.2.2
- purpeille 3.2.0+fabric-1.19
- purpurclient 1.19.2-10
- puzzle 1.4.0-1.19
- puzzle-base 1.4.0-1.19 via puzzle
- puzzle-gui 1.4.0-1.19 via puzzle
- puzzle-models 1.4.0-1.19 via puzzle
- puzzle-splashscreen 1.4.0-1.19 via puzzle
- puzzleslib 4.3.0
- qu-enchantments 1.2.2-1.19
- quarrymod 1.0.2
- raised 1.1.2
- raknetify 0.1.0+alpha.5.15
- reborncore 5.3.4 via techreborn
- redstonelantern 1.0+1.19
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- regenerations 1.0.2
- replaymod 1.19.1-2.6.8
- resclone 1.10.1
- retino 1.0.1
- revelationary 1.0.2
- rhino 1802.1.14-build.225
- rightclickharvest 3.0.1
- rocks 1.6.1
- roughlyenoughitems 9.1.530
- rpgstats 4.3.15+1.19
- rpmtw_platform_mod 1.4.3
- sandwichable 1.3.a+1.19
- satin 1.8.0 via blur
- secretrooms 1.3.2+1.19
- serbanmod 1.0.3-1.19
- server_translations_api 1.4.17+1.19.2 via biometech
- servercore 1.3.1-1.19.1
- servertick 1.7
- sgui 1.1.5+1.19.1 via biometech
- silencemobs-fabric 2.6
- simpleshulkerpreview 2.0
- skinlayers 1.5.1-mc1.19.1
- slumber 1.0
- smoothboot 1.19-1.7.1
- sod 22.8.7-MC1.19.2
- sodium 0.4.4+build.18
- sodium-extra 0.4.10+mc1.19.2-build.64
- sort 1.0.1
- soundcategories 1.2.4+1.19 via extrasounds
- spikyspikes 4.0.1
- spruceui 4.0.0+1.19 via sandwichable
- sspb 3.1.0
- starlight 1.1.1+fabric.ae22326
- stepup 1.19.1-fabric0.58.5-1.1
- stoneholm 1.4.4
- striders-grace 1.0.0
- structurized-reborn 1.19-01 via amethyst_imbuement
- sulphate 1.1.1 via cosmetica
- symbol-chat 0.3.2
- t_and_t 1.8.2
- tdcdata 0.1.3+1.19
- team_reborn_energy 2.2.0 via wiredredstone
- techreborn 5.3.4
- terrablender 2.0.0.120 via traverse
- terraform-biome-remapper-api-v1 4.1.1 via traverse
- terraform-config-api-v1 4.1.1 via traverse
- terraform-surfaces-api-v1 4.1.1 via traverse
- terraform-tree-api-v1 4.1.1 via traverse
- terraform-wood-api-v1 4.1.1 via traverse
- textile_backup 2.4.0-1.19
- thorium 1.3.2
- totw_additions 1.2.3
- trailblazer 0.1.0+1.19.2
- traverse 6.0.0
- traverse-client 6.0.0 via traverse
- traverse-common 6.0.0 via traverse
- traverse-worldgen 6.0.0 via traverse
- trinkets 3.4.0
- tropics 0.1.4
- tweed4_annotated 1.3.1+mc22w17a via wandering_collector
- tweed4_base 1.6.0+mc22w17a via wandering_collector
- tweed4_data 1.2.1+mc22w17a via wandering_collector
- tweed4_data_hjson 1.1.1+mc22w17a via wandering_collector
- tweed4_tailor_coat 1.1.3+mc22w17a via wandering_collector
- tweed4_tailor_screen 1.1.1+mc22w17a via wandering_collector
- twigs 2.0.0-beta.9+1.19-fabric
- vcinteraction 1.19.2-1.0.2
- villager-hats 1.4.1
- villagernames-fabric 4.0
- vmp 0.2.0+beta.7.0
- voicechat 1.19.2-2.3.8
- voidcrafting 1.7.2+fabric-1.19
- voidtotem 2.1.0
- walllanterns 1.3.0-1.19
- wandering_collector 1.1.3+mc1.19
- wardentools 1.6
- warpsigns 1.19.2-0.1.1
- waveycapes 1.2.1
- wilderwild 1.0.5-Fabric+1.19.2
- windchimes 1.2.1
- wiredredstone 0.4.8+1.19
- woof 1.1.2-1.18
- world-gen 1.0.1
- wthit 5.11.3
- yigd 1.4.2
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.9

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
Incompatible with a mod

**Comment by Encode42** [comment] 2022-09-05 17:51
Duplicate of #17

**Closed by Encode42** 2022-09-05 17:51 UTC
